### ISSUE TITLE
empty-dashboard ISS within Home Assistant

### ISSUE THREAD

**Issue by Tobe2d** [tiberiushunter/hassio-config#48]
Hi,

Thank you so much for the super guide ISS within Home Assistant on your website.

I follow the steps closely and created everything moving one step at a time and I end up with working map but empty dashboard for the informations. check the screenshot below:

![image](https://user-images.githubusercontent.com/4099839/141046154-6775e0bd-57f1-4a2d-ad59-ad04c643d9f4.png)

Could you help on this if the guide need some update or something?

**Comment by tiberiushunter** [comment]
Hi, 

Sorry for the delay in getting back to you, I didn't see the notification come through 🙈 

Just having a look at this, comparing with my own set up - it looks as though it's the `ISS Pass Times` sensor that isn't pulling data in correctly. What have you set  as the `resource` in the below section: 

```
- platform: rest
  name: ISS Pass times
  json_attributes:
    - request
    - response
  value_template: >
    {{ value_json.message }}
  resource: 'http://api.open-notify.org/iss-pass.json?lat=51.5007&lon=0.1246'
  scan_interval:
    seconds: 300
```

Also under the History tab can you see if the `sensor.iss_risetime_0` is storing the times locally for you?
